### ISSUE TITLE
Handle irregular camelCase to snake_case conversion

### ISSUE THREAD

**Issue by kazk** [kube-rs/k8s-pb#2]
Some irregular camel case to snake case conversions are failing (e.g., `clusterIPs` becomes `cluster_i_ps`). But `prost_build` doesn't provide a way to fix this at the moment.

**Comment by clux** [comment]
Is there an upstream issue for this? Had a bit of a look, and nothing matching AFAIKT. But I did see people saying they could inject serde annotations to certain types in the config with https://docs.rs/prost-build/0.9.0/prost_build/struct.Config.html#method.type_attribute :

```rust
let mut config = prost_build::Config::new();
config.type_attribute(".", "#[derive(Serialize)]");
config.type_attribute(".", "#[serde(rename_all = \"camelCase\")]");
```

also there are people over the output to do stuff ([here just a rename](https://github.com/tokio-rs/prost/issues/173#issuecomment-509004188)) we could in the worst-case to a search and replace on the file :|

Anyway, if there is no upstream issue for this we should raise one if needed.

**Comment by kazk** [comment]
I don't think so. https://github.com/tokio-rs/prost/issues/207 is kind of similar (preserving the original name can be done by passing an identity function).

**Comment by clux** [comment]
Looking at this again. We can technically just mass replace known broken names at the end.

I'm considering doing this for the type names in https://github.com/kube-rs/k8s-pb/pull/49 for alignment with type names in k8s-openapi.
